[package]
name = "lightning-signer-server"
version = "0.1.0-5"
authors = ["Devrandom <c1.devrandom@niftybox.net>", "Ken Sedgwick <ken@bonsai.com>"]
edition = "2018"
license = "Apache-2.0"
description = "A library for implementing a Lightning signer server, dependent on the lightning-signer-core crate."
homepage = "https://gitlab.com/lightning-signer/docs/"
repository = "https://gitlab.com/lightning-signer/validating-lightning-signer"
readme = "../README.md"

[features]
default = ["grpc", "persist_kv_json"]
grpc = ["tokio", "tonic", "prost", "serde", "serde_json", "clap", "lightning-signer-core/grpc"]
persist_kv_json = [ "kv", "serde", "serde_json", "serde_with", "bitcoin/use-serde" ]
log_pretty_print = []
chain_test = ["clap", "url", "jsonrpc-async", "async-trait"]
test_utils = ["lightning-signer-core/test_utils"]

[lib]
name = "lightning_signer_server"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
log = { version="0.4.14", features = [ "std" ] }
time = "0.2"
lightning-signer-core = { path = "../lightning-signer-core", features = ["debug", "test_utils"] }
backtrace = "0.3"
bip39 = {version = "1.0.0", features = ["rand"] }
hex = "0.3.2"
rand = "0.4"
kv = { version = "0.22.0", features = ["json-value"], optional = true }
tonic = { version = "0.4", optional = true }
prost = { version = "0.7", optional = true }
hyper = "=0.14.4"  # 0.14.5 depends on socket2 0.4 which requires a higher MSRV
tokio = { version = "1.6", features = ["macros", "rt-multi-thread"], optional = true }
serde = { version = "1.0.105", features = ["derive"], optional = true }
serde_json = { version = "1.0.48", optional = true }
serde_with = { version = "1.6.4", features = ["hex"], optional = true }
clap = { version = "3.0.0-beta.2", optional = true }
bitcoin = { version = "0.27", features = ["bitcoinconsensus"]}
ctrlc = { version = "3.1.9", features = ["termination"] }
triggered = "0.1.1"

url = { version = "2.2", optional = true }
jsonrpc-async = { version = "2.0", optional = true }
async-trait = { version = "0.1", optional = true }

# For logging in unit tests
test-env-log = "0.2.3"
env_logger = "0.9.0"

[dev-dependencies]
tempfile = "3.2.0"

[build-dependencies]
tonic-build = "0.4"

[[bin]]
name = "client"
path = "src/client_main.rs"
required-features = ["grpc"]

[[bin]]
name = "server"
path = "src/server_main.rs"
required-features = ["grpc"]

[[bin]]
name = "persist_test"
path = "src/persist_test_main.rs"
required-features = ["persist_kv_json", "test_utils"]

[[bin]]
name = "chain_test"
path = "src/chain_test_main.rs"
required-features = ["chain_test"]
